#! /usr/bin/env python
from time import sleep
import rospy

from defusedxml.ElementTree import fromstring

from urdf2mjcf.core import _parse_element as parse_stream, tostring, full_pipeline


if __name__ == "__main__":
    rospy.init_node("urdf2mjcf")

    urdf_path = rospy.get_param("urdf_source", "robot_description")
    xml_destination = rospy.get_param("xml_destination", "mujoco_xml")

        while not rospy.has_param(urdf_path) and not rospy.is_shutdown():
            sleep(0.1)

    urdf = rospy.get_param(urdf_path)
    sensor_config = rospy.get_param("sensor_config", None)
    mujoco_node = rospy.get_param("mujoco_node", None)

    element = fromstring(urdf)

    result = full_pipeline(
        fromstring(urdf),
        sensor_config=parse_stream(sensor_config),
        mujoco_node=parse_stream(mujoco_node),
    )

    rospy.set_param(xml_destination, tostring(result, encoding="unicode"))
